[package]
name = "inventory"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { version = "7", features = ["bson", "chrono"] }
async-graphql-rocket = { version = "7" }
rocket = { version = "0.5", features = ["json"] }
anyhow = "1.0.98"
